model:
  dim: 64
  dim_mults: [1, 2, 4, 8]
  num_classes: 1
  cond_drop_prob: 0

diffusion:
  image_size: 64
  timesteps: 1000
  sampling_timesteps: 8
  beta_schedule: linear
  objective: pred_x0

dataset:
  train_folder: RS_Real/train
  test_folder: RS_Real/test/npz
  image_size: 64
  augment_horizontal_flip: false

trainer:
  train_batch_size: 64
  test_batch_size: 2
  train_lr: 0.0001
  train_num_steps: 150000
  gradient_accumulate_every: 2
  ema_decay: 0.995
  amp: false
  save_and_sample_every: 5000
  results_folder: result_RS_Real
  log_path : RS_Real

test:
  save_path: rs_real_result    
  checkpoint: checkpoint/RS_Real.pt