# In config/train_official_data_config.yaml

model:
  dim: 64
  dim_mults: [1, 2, 4, 8]
  num_classes: 1
  cond_drop_prob: 0

diffusion:
  image_size: 128 # The original model was trained at 256x256
  timesteps: 1000
  sampling_timesteps: 8
  beta_schedule: linear
  objective: pred_x0

dataset:
  train_folder: /workspace/RSD/RS-Diffusion/train # <-- Path to your folder with all the .npz files
  test_folder: /workspace/RSD/RS-Diffusion/test # We can use the same for testing/sampling
  image_size: 128 # <-- Must match the size in the diffusion section
  augment_horizontal_flip: true

trainer:
  train_batch_size: 28
  test_batch_size: 8
  train_lr: 0.0001
  train_num_steps: 200000 # Total training steps. 200k is a good long run.
  gradient_accumulate_every: 3
  ema_decay: 0.995
  amp: true
  save_and_sample_every: 5000 # Saves a checkpoint every 5000 steps
  results_folder: /workspace/RSD/my_trained_models # <-- Folder where your new .pt files will be saved
  log_path: my_first_training_run # Name for the wandb log
